spring.application.name=your_application_name

logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
logging.level.root=${LOG_LEVEL:INFO}
logging.file.name=${LOG_FILE_NAME:C:/sticker-factory-logs/application.log}
logging.pattern.file={"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","logger":"%c","message":"%m"}


spring.datasource.url=jdbc:postgresql://localhost:5432/your_db_name
spring.datasource.username=your_username
spring.datasource.password=your_pwd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.security.user.name=${STICKERFACTORY_USERNAME:harsh}
#spring.security.user.password=${STICKERFACTORY_PASSWORD:harshpwd}
#spring.security.user.roles=${STICKERFACTORY_ROLES:USER,ADMIN}

spring.profiles.active=prod

stripe.apiKey=${STRIPE_API_KEY:sk_test_your_api_key}